// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} streamMessage
 * @param {string} chatContextGUID
 * @returns {Promise.<boolean>}
 */
export async function JS_SubmitChatForStreaming(streamMessage, chatContextGUID) {
	// BEGIN USER CODE
	const baseUrl = mx.appUrl;
	const endpoint = `${baseUrl}llm-streaming`;
	const response = await fetch(endpoint, {
		method: "POST",
		headers: {			
			"Content-Type": "application/json",
			"Accept": "text/event-stream"
		},
		body: JSON.stringify({
			chatContextGUID: chatContextGUID
		})
	})

	// Check if the response status is 404
	if (response.status == 404) {
		console.error(`The URL '${endpoint}' could not be found (HTTP 404). This might indicate that the microflow 'ConversationalUI.ASU_Streaming' was not added to the after startup microflow. Please ensure that the 'ConversationalUI.ASU_Streaming' microflow is executed before any streaming related action.`);
		return false;
	}

	const reader = response.body.getReader();
	const decoder = new TextDecoder('utf-8');
	let buffer = ''; // Buffer to accumulate incomplete SSE messages

	// Function to process a complete SSE message
	const processSseMessage = (message) => {
		// SSE messages typically look like:
		// id: 1
		// event: update
		// data: {"status": "online", "value": 123}
		//
		// data: {"status": "offline"}
		//
		// (empty line indicates end of message)

		const lines = message.replace(/\r\n/g, "\n").split("\n").filter(line => line.trim() !== "");
		let id = null;
		let event = 'message'; // Default event type
		let data = '';
		let deleteContent = false;
		let throwError = false;

		for (const line of lines) {
			if (line.startsWith('id:')) {
				id = line.substring(3).trim();
			} else if (line.startsWith('event:')) {
				event = line.substring(6).trim();
			} else if (line.startsWith('data:')) {
				// Accumulate data lines, they can be multi-line
				data += line.substring(5).trim();
			} else if (line.startsWith('deleteContent:')) {
				const value = line.substring(14).trim();
				deleteContent = value === 'true';
			} else if (line.startsWith('throwError:')) {
				const value = line.substring(11).trim();
				throwError = value === 'true';
			}
			// You might also handle 'retry:' fields if your server sends them
		}

		if (throwError) {
				throw new Error();
		}
		if (deleteContent) {
				streamMessage.set("Content", "");
		}
		if (data) {
			try {
				const binary = atob(data);
				const bytes = Uint8Array.from(binary, c => c.charCodeAt(0));
				const decodedData = new TextDecoder("utf-8").decode(bytes);
				// Here you would update your UI or application state
				const currentText = streamMessage.get("Content")
				streamMessage.set("Content", currentText + decodedData)
				
  				// Auto-scroll if at bottom (batched with requestAnimationFrame for smoothness)
  				if (!window.scrollPending) {
      				window.scrollPending = true;
      				requestAnimationFrame(() => {
          				const container = document.querySelector('.messages-container');
          					if (container && !container.classList.contains('not-at-bottom')) {
              						container.scrollTop = container.scrollHeight; // Instant, no 'smooth'
          						}
		          			window.scrollPending = false;
      					});
  				}  
				
			} catch (e) {
				console.warn('Could not parse SSE data as JSON:', data, e);
				// Handle non-JSON data if expected
				updateUIWithStreamData(data, event);
			}
		}
	};

	try {
		while (true) {
			const { done, value } = await reader.read();

			if (done) {
				console.log('Stream finished.');
				break;
			}

			// Decode the chunk and add to buffer
			buffer += decoder.decode(value, { stream: true });
			buffer = buffer.replace(/\r\n/g, "\n");

			// Process complete SSE messages from the buffer
			// SSE messages are terminated by two newline characters (\n\n)
			let messageEndIndex;
			while ((messageEndIndex = buffer.indexOf('\n\n')) !== -1) {
				const message = buffer.substring(0, messageEndIndex);
				processSseMessage(message);
				buffer = buffer.substring(messageEndIndex + 2); 
			}
		}
		return true;
	} catch (error) {
		return false;
	}

	// END USER CODE
}
