// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function JS_ScrollToUserMessageIfAtBottom() {
	// BEGIN USER CODE
      const container = document.querySelector('.messages-container');                                                                                                                                                                           
      if (container) {                                                                                                                                                                                                                           
          // Check if user was at bottom using the class                                                                                                                                                                                         
          const wasAtBottom = !container.classList.contains('not-at-bottom');                                                                                                                                                                    
                                                                                                                                                                                                                                                 
          if (wasAtBottom) {                                                                                                                                                                                                                     
              // Scroll to bottom to show the user's message                                                                                                                                                                                     
              container.scrollTop = container.scrollHeight;                                                                                                                                                                                      
              console.log('Scrolled to user message');                                                                                                                                                                                           
          }                                                                                                                                                                                                                                      
      }                                                                                                                                                                                                                                          
	// END USER CODE
}
