// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function JS_ToggleScrollButton() {
	// BEGIN USER CODE
  function waitForElement(selector, callback) {
    const element = document.querySelector(selector);
    if (element) {
      callback(element);
    } else {
      setTimeout(() => waitForElement(selector, callback), 50);
    }
  }

  waitForElement('.messages-container', (container) => {
    console.log('Scroll handler attached');

    // Check initial state
    const checkScrollPosition = () => {
      const isAtBottom = container.scrollTop + container.clientHeight >= container.scrollHeight - 100;

      if (isAtBottom) {
        container.classList.remove('not-at-bottom');
      } else {
        container.classList.add('not-at-bottom');
      }
    };

    // Set initial state
    checkScrollPosition();

    // Update on scroll
    container.addEventListener('scroll', checkScrollPosition);

    // Store reference globally
    window.chatScrollSetup = { container };
  });
	// END USER CODE
}
