// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package conversationalui.actions;

import conversationalui.impl.MxLogger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;
import genaicommons.impl.ResponseConnectionController;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.externalinterface.connector.RequestHandler;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Initializes the request handler that acts as the entry point for the streaming request from the UI and opens the SSE connection for the response stream. 
 */
public class InitAsyncStreamHandler extends UserAction<java.lang.Void>
{
	public InitAsyncStreamHandler(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		Core.addRequestHandler("llm-streaming", new RequestHandler() {
			@Override
			protected void processRequest(IMxRuntimeRequest req, IMxRuntimeResponse resp, String s) throws Exception {
				
				LOGGER.debug("Request handler started.");
				
                // Configure response for Server-Sent Events
                resp.setContentType("text/event-stream");
                resp.getHttpServletResponse().setStatus(200);
                
                LOGGER.debug("Configure response for Server-Sent Event");

                // Generate unique request ID for streaming
                String streamingResponseWriterId = UUID.randomUUID().toString();
                ResponseConnectionController.getInstance().addStreamingResponseWriter(streamingResponseWriterId,
                        new ResponseConnectionController.StreamingResponseWriter(resp.getOutputStream()));
                
                LOGGER.debug("Generated unique request ID for streaming");
                
	            // Parse JSON request body
	            String jsonInput = new String(req.getInputStream().readAllBytes());
	            ObjectMapper objectMapper = new ObjectMapper();
	            try {
	            	JsonNode jsonRequest = objectMapper.readTree(jsonInput);
	            	
	                // Extract fields from JSON
	                String chatContextGUID = jsonRequest.get("chatContextGUID").asText();
	                
	                // Create user context from session
	                String sessionId;
	                String host = req.getHeader("Host");
	                if (host.contains("localhost")) {
	                	sessionId = req.getCookie("XASSESSIONID");
	                } else {
	                	sessionId = req.getCookie("__Host-XASSESSIONID");
	                }
	                ISession session = Core.getSessionById(UUID.fromString(sessionId));
	                IContext ctx = session.createContext();
	                
	                // Retrieve chat context from database using id
	                List<IMendixObject> resultsChatContext = Core.createXPathQuery("//ConversationalUI.ChatContext[id=$value]")
	                        .setVariable("value", chatContextGUID)
	                        .execute(ctx);
	                
	                if (resultsChatContext.isEmpty()) {
	                    resp.getHttpServletResponse().setStatus(400);
	                    throw new NullPointerException("Chat context not found for: " + chatContextGUID);
	                }
	                
	                conversationalui.proxies.ChatContext mxChatContext = conversationalui.proxies.ChatContext.initialize(ctx, resultsChatContext.get(0));
	                
	                agentcommons.proxies.Version mxVersion = conversationalui.proxies.microflows.Microflows.chatContext_GetVersion(getContext(), mxChatContext);
	                
	                if (mxVersion == null) {
	                    resp.getHttpServletResponse().setStatus(400);
	                    throw new NullPointerException("Version could not be found.");
	                }
	                
	                if (mxVersion.getVersion_DeployedModel() == null) {
	                    resp.getHttpServletResponse().setStatus(400);
	                    throw new NullPointerException("Deployed Model could not be found.");
	                }
	                
	                boolean isAgentBuilderTest = agentcommons.proxies.microflows.Microflows.chatContext_IsAgentEditor(ctx, mxChatContext);

	                // First validate pre- and postprocessing microflows
	                if (!isAgentBuilderTest) {
	                	if (mxVersion.getPreProcessingMicroflow() != null && !mxVersion.getPreProcessingMicroflow().isBlank()) {
	                		validate_preprocessing_microflow(mxVersion.getPreProcessingMicroflow());
	            		}
	                	if (mxVersion.getPostProcessingMicroflow() != null && !mxVersion.getPostProcessingMicroflow().isBlank()) {
	                		validate_postprocessing_microflow(mxVersion.getPostProcessingMicroflow());
		                }
            		}
	                
	                // Construct request from ChatContex by using PreProcessing microflow
	                genaicommons.proxies.Request mxRequest = null;
	                if (isAgentBuilderTest) {
	                	mxRequest = agentcommons.proxies.microflows.Microflows.chatContext_PreProcessing_AgentBuilder(ctx, mxChatContext);
	                } else {
	                	if (mxVersion.getPreProcessingMicroflow() != null && !mxVersion.getPreProcessingMicroflow().isBlank()) {
	                		IMendixObject mxRequestObject = Core.microflowCall(mxVersion.getPreProcessingMicroflow())
									.withParam("ChatContext", mxChatContext)
									.execute(ctx);
			                
			                mxRequest = genaicommons.proxies.Request.initialize(ctx, mxRequestObject);
	                	} else {
	                		mxRequest = conversationalui.proxies.microflows.Microflows.chatContext_DefaultPreProcessing_Agent(ctx, mxChatContext);
	                	}
	                }
	                
	                if (mxRequest == null) {
	                    resp.getHttpServletResponse().setStatus(400);
	                    throw new NullPointerException("Request could not be created from ChatContext by running the PreProcessing microflow.");
	                }

	                LOGGER.debug("Successfully created Request " + mxRequest);
	                
	                mxRequest.setStreamingResponseWriterId(streamingResponseWriterId);
						
					genaicommons.proxies.Response mxResponse = genaicommons.proxies.microflows.Microflows.chatCompletions_WithHistory(ctx, mxRequest, mxVersion.getVersion_DeployedModel());
					
					if (mxResponse == null) {
	                    resp.getHttpServletResponse().setStatus(500);
	                    LOGGER.debug("There was an issue when calling the Chat Completions API, no response was returned.");
		            	genaicommons.impl.StreamingImpl.throwError(getContext(),resp.getOutputStream());
	                    ResponseConnectionController.getInstance().removeStreamingResponseWriter(streamingResponseWriterId);
	                    return;
	                }
					
					LOGGER.debug("Chat with history completed.");
					
					// run Post Processing microflow with ChatContext and Response
					if (isAgentBuilderTest) {
						conversationalui.proxies.microflows.Microflows.chatContext_DefaultPostProcessing(ctx, mxChatContext, mxResponse);
					} else {
						if (mxVersion.getPostProcessingMicroflow() != null && !mxVersion.getPostProcessingMicroflow().isBlank()) { 
							Core.microflowCall(mxVersion.getPostProcessingMicroflow())
									.withParam("Response", mxResponse)
									.withParam("ChatContext", mxChatContext)
									.execute(ctx);
						} else {
							conversationalui.proxies.microflows.Microflows.chatContext_DefaultPostProcessing(ctx, mxChatContext, mxResponse);
						}
					}
					ResponseConnectionController.getInstance().removeStreamingResponseWriter(streamingResponseWriterId);
					LOGGER.debug("Request handler ended.");
	            	
	            } catch (Exception e) {
	            	LOGGER.error(e);
	            	genaicommons.impl.StreamingImpl.throwError(getContext(),resp.getOutputStream());
                    ResponseConnectionController.getInstance().removeStreamingResponseWriter(streamingResponseWriterId);
	            }
				
			}
		});
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "InitAsyncStreamHandler";
	}

	// BEGIN EXTRA CODE
	 private static final MxLogger LOGGER = new MxLogger(InitAsyncStreamHandler.class);

	 private static void validate_preprocessing_microflow(String microflow) {
		 
		List<String> microflowNameList = new ArrayList<>();
		 
		Core.getMicroflowNames().stream()
			.filter(microflowName -> microflowName.contentEquals(microflow))
			.forEach(microflowName -> microflowNameList.add(microflowName));
		
		if (microflowNameList.isEmpty()) {
			throw new IllegalArgumentException("The microflow set as the PreProcessingMicroflow in Version, could not be found.\nCurrently set microflow: " + microflow);
		}
		
		java.util.Map<String, IDataType> inputParameters = new HashMap<>();
		inputParameters.put("ChatContext", Core.createDataType("ConversationalUI.ChatContext"));
		
		Boolean microflowHasCorrectInputParams = Core.getInputParameters(microflowNameList.getFirst()).equals(inputParameters);
		
		Boolean microflowHasCorrectOutputParam = Core.getReturnType(microflowNameList.getFirst()).getType().equals(IDataType.DataTypeEnum.Object) && Core.getReturnType(microflow).getObjectType().equals("GenAICommons.Request");
		
		if (microflowHasCorrectInputParams && microflowHasCorrectOutputParam) {
			return;
		} else {
			String errorMessage = "";
			if (!microflowHasCorrectInputParams) {
				errorMessage += "The microflow set as the PreProcessingMicroflow in Version does not have the correct input parameters. It must have a ConversationalUI.ChatContext object as an input parameter.\n";
			}
			if (!microflowHasCorrectOutputParam) {
				errorMessage += "The microflow set as the PreProcessingMicroflow in Version does not have the correct output parameter. It must have a GenAICommons.Request object as the output parameter.\n";
			}
			throw new IllegalArgumentException(errorMessage);
		}
	 }
	 
	 private static void validate_postprocessing_microflow(String microflow) {
		 
		 List<String> microflowNameList = new ArrayList<>();
			 
		 	Core.getMicroflowNames().stream()
				.filter(microflowName -> microflowName.contentEquals(microflow))
				.forEach(microflowName -> microflowNameList.add(microflowName));
			
			if (microflowNameList.isEmpty()) {
				throw new IllegalArgumentException("The microflow set as the PostProcessingMicroflow in Version, could not be found.\nCurrently set microflow: " + microflow);
			}
			
			java.util.Map<String, IDataType> inputParameters = new HashMap<>();
			inputParameters.put("Response", Core.createDataType("GenAICommons.Response"));
			inputParameters.put("ChatContext", Core.createDataType("ConversationalUI.ChatContext"));
			
			Boolean microflowHasCorrectInputParams = Core.getInputParameters(microflowNameList.getFirst()).equals(inputParameters);
			
			Boolean microflowHasCorrectOutputParam = Core.getReturnType(microflowNameList.getFirst()).getType().equals(IDataType.DataTypeEnum.Nothing);
			
			if (microflowHasCorrectInputParams && microflowHasCorrectOutputParam) {
				return;
			} else {
				String errorMessage = "";
				if (!microflowHasCorrectInputParams) {
					errorMessage += "The microflow set as the PostProcessingMicroflow in Version does not have the correct input parameters. It must have a ConversationalUI.ChatContext object and a GenAICommons.Response object as input parameters.\n";
				}
				if (!microflowHasCorrectOutputParam) {
					errorMessage += "The microflow set as the PostProcessingMicroflow in Version does not have the correct output parameter. It must not have any output parameter.\n";
				}
				throw new IllegalArgumentException(errorMessage);
			}
		 }
	 
	// END EXTRA CODE
}
