// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agentcommons.actions;

import java.util.stream.Collectors;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import agentcommons.proxies.Microflow;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class Microflow_GetList extends UserAction<java.util.List<IMendixObject>>
{
	public Microflow_GetList(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.util.List<IMendixObject> modelMicroflowList = Core.getMicroflowNames().stream()
				.filter(microflowName -> !microflowName.isBlank() && microflowName.contains("."))
				.sorted()
				.map(microflowName -> {
					IMendixObject microflowImport = Core.instantiate(getContext(), Microflow.getType());
		        	String[] parts = microflowName.split("\\.", 2);
		        	microflowImport.setValue(getContext(), Microflow.MemberNames.FullName.toString(), microflowName);
		        	microflowImport.setValue(getContext(), Microflow.MemberNames.ModuleName.toString(), parts[0]);
		        	microflowImport.setValue(getContext(), Microflow.MemberNames.MicroflowName.toString(), parts[1]);
		        	return microflowImport;
				})
				.collect(Collectors.toList());
		
		return modelMicroflowList; 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Microflow_GetList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
