// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agentcommons.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import agentcommons.impl.MxLogger;
import agentcommons.proxies.PromptToUse;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Use this action to update the system prompt of your request based on an agent that was configured in the app. When you pass a context object, all variables that match the variables used in the prompt text are replaced with the actual values extracted from the attributes with the exact same name as a variable. String, integer/long, decimal, date time, boolean and enum attribute types are supported. Note that for ENUM attributes the key will be used to replace a variable. To ensure a fixed format (for other types than string), it is recommended to convert values to type string first and only pass string attributes for value replacement.
 */
public class Request_UpdateWithContextObject extends UserAction<java.lang.Void>
{
	/** @deprecated use Agent.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Agent;
	private final agentcommons.proxies.Agent Agent;
	private final IMendixObject ContextObject;
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;

	public Request_UpdateWithContextObject(
		IContext context,
		IMendixObject _agent,
		IMendixObject _contextObject,
		IMendixObject _request
	)
	{
		super(context);
		this.__Agent = _agent;
		this.Agent = _agent == null ? null : agentcommons.proxies.Agent.initialize(getContext(), _agent);
		this.ContextObject = _contextObject;
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Agent, "Agent is required.");
			requireNonNull(ContextObject, "ContextObject is required.");
			requireNonNull(Request, "Request is required.");

			IMendixObject promptObject = Core.userActionCall("AgentCommons." + PromptToUse_GetAndReplace.class.getSimpleName())
					.withParams(Agent.getMendixObject(), ContextObject)
					.execute(getContext());
			if (promptObject == null) {
				return null;
			}
			PromptToUse promptToUse = PromptToUse.initialize(getContext(), promptObject);
			
			Request.setSystemPrompt(promptToUse.getSystemPrompt());
			
			return null;

		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_UpdateWithContextObject";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Request_UpdateWithContextObject.class);

	
	// END EXTRA CODE
}
