// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.MCP;
import genaicommons.impl.ToolCollectionImpl;
import genaicommons.proxies.ArgumentInput;
import genaicommons.proxies.Tool;
import genaicommons.proxies.ToolCollection;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Adds a new MCPTool to a Request.
 * Parameters: 
 * - Request: The request to add the tool to.
 * - Name: The name of the tool to call.
 * - Description (optional): A description of what the tool does, used by the model to choose when and how to call the tool.
 * - ArgumentInputList (optional): describe the input parameters of a tool.
 * 
 * The action returns empty if adding the tool was not successful (errors are logged).
 */
public class Request_AddMCPTool extends UserAction<IMendixObject>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	/** @deprecated use MCPServerConfiguration.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPServerConfiguration;
	private final mcpclient.proxies.MCPServerConfiguration MCPServerConfiguration;
	/** @deprecated use Tool.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Tool;
	private final mcpclient.proxies.Tool Tool;

	public Request_AddMCPTool(
		IContext context,
		IMendixObject _request,
		IMendixObject _mCPServerConfiguration,
		IMendixObject _tool
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.__MCPServerConfiguration = _mCPServerConfiguration;
		this.MCPServerConfiguration = _mCPServerConfiguration == null ? null : mcpclient.proxies.MCPServerConfiguration.initialize(getContext(), _mCPServerConfiguration);
		this.__Tool = _tool;
		this.Tool = _tool == null ? null : mcpclient.proxies.Tool.initialize(getContext(), _tool);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try{
			requireNonNull(Request, "Request is required.");
			requireNonNull(MCPServerConfiguration, "MCPServerConfiguration is required.");
			requireNonNull(Tool, "Tool is required.");
			
			ToolCollection toolCollection = ToolCollectionImpl.getOrCreateToolCollection(getContext(), Request);
			
			return createMCPTool(toolCollection).getMendixObject();

		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_AddMCPTool";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Request_AddMCPTool.class);
	
	private MCP createMCPTool(ToolCollection toolCollection) throws CoreException {
		MCP tool = new MCP(getContext());
		
		tool.setMicroflow("MCPClient.MCPClient_ToolMicroflow");
		tool.setTool_ArgumentInput(createArgumentInputList());
		tool.setDescription(Tool.getDescription());
		tool.setName(Tool.getName());
		tool.setMCP_MCPServerConfiguration(MCPServerConfiguration);
		List<Tool> ToolList = toolCollection.getToolCollection_Tool();
		ToolList.add(tool);
		toolCollection.setToolCollection_Tool(ToolList); 
		return tool;
	}
	
	private List<ArgumentInput> createArgumentInputList (){
		return mcpclient.proxies.microflows.Microflows.tool_CreateArgumentInputList(getContext(), Tool);
	}
	// END EXTRA CODE
}
