// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agenteditorcommons.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import agenteditorcommons.impl.AgentDocumentUtils;
import agenteditorcommons.impl.MxLogger;
import agentcommons.actions.Agent_Call_WithoutHistory;

/**
 * This action calls the Agent with the specified request. It executes a Chat Completions operation based on the defined Agent. All agent configurations, such as the selected model, system prompt or user prompt are used. 
 * If a request object is passed that already contains a system prompt, or a value for the parameters temperature, top P or max tokens, those values have priority and will not be overwritten by the agent configurations.
 * If a context object is passed, all variables are replaced in the system and user prompt. A response is returned that contains the final assistant's message.
 */
public class Agent_CallDocument_WithoutHistory extends UserAction<IMendixObject>
{
	private final java.lang.String Agent;
	private final IMendixObject OptionalContextObject;
	/** @deprecated use OptionalRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __OptionalRequest;
	private final genaicommons.proxies.Request OptionalRequest;
	/** @deprecated use OptionalFileCollection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __OptionalFileCollection;
	private final genaicommons.proxies.FileCollection OptionalFileCollection;

	public Agent_CallDocument_WithoutHistory(
		IContext context,
		java.lang.String _agent,
		IMendixObject _optionalContextObject,
		IMendixObject _optionalRequest,
		IMendixObject _optionalFileCollection
	)
	{
		super(context);
		this.Agent = _agent;
		this.OptionalContextObject = _optionalContextObject;
		this.__OptionalRequest = _optionalRequest;
		this.OptionalRequest = _optionalRequest == null ? null : genaicommons.proxies.Request.initialize(getContext(), _optionalRequest);
		this.__OptionalFileCollection = _optionalFileCollection;
		this.OptionalFileCollection = _optionalFileCollection == null ? null : genaicommons.proxies.FileCollection.initialize(getContext(), _optionalFileCollection);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			IMendixObject agentIMendixObject = AgentDocumentUtils.getAgentObjectFromDocument(Agent, getContext());
			IMendixObject requestIMendixObject = OptionalRequest == null ? null : OptionalRequest.getMendixObject();
			IMendixObject fileCollectionIMendixObject = OptionalFileCollection == null ? null : OptionalFileCollection.getMendixObject();
			
			return Core.userActionCall("AgentCommons." + Agent_Call_WithoutHistory.class.getSimpleName())
					.withParams(agentIMendixObject, OptionalContextObject, requestIMendixObject, fileCollectionIMendixObject)
					.execute(getContext());
			
		} catch (Exception e) {
		    LOGGER.error(e);
		    return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Agent_CallDocument_WithoutHistory";
	}

	// BEGIN EXTRA CODE
	
	private static final MxLogger LOGGER = new MxLogger(Agent_CallDocument_WithoutHistory.class);

	// END EXTRA CODE
}
