// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agenteditorcommons.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import agenteditorcommons.impl.AgentDocumentUtils;
import agenteditorcommons.impl.AgentEditorTestServlet;
import agenteditorcommons.impl.AgentEditorSyncServlet;
import agenteditorcommons.impl.MxLogger;

/**
 * Imports all defined documents (such as agents and models) to the app's database so that they can be viewed at runtime and integrate with Agent Commons, Token Monitor, Observability etc.
 * This action can be used as part of your app's after startup logic.
 */
public class AgentEditor_ImportFromStudioPro extends UserAction<java.lang.Boolean>
{
	public AgentEditor_ImportFromStudioPro(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			LOGGER.info("Starting AgentEditor_ASU.");
			
			AgentDocumentUtils.importAllModelDocuments(getContext());
			
			registerServlet();

			LOGGER.info("Finished AgentEditor_ASU.");
			return true;
		} catch (Exception e) {
			LOGGER.error(e);
			return false;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AgentEditor_ImportFromStudioPro";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(AgentEditor_ImportFromStudioPro.class);
	private static boolean servletRegistered = false;

	private void registerServlet() {
		if (!servletRegistered) {
			Core.addDevelopmentServlet("preview_agent_test", new AgentEditorTestServlet());
			Core.addDevelopmentServlet("preview_agent_sync", new AgentEditorSyncServlet());
			servletRegistered = true;
			LOGGER.debug("AgentEditor development servlets registered.");
		}
	}


	// END EXTRA CODE
}
