// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agenteditorcommons.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import agentcommons.actions.Agent_Call_WithHistory;
import agentcommons.impl.MxLogger;
import agenteditorcommons.impl.AgentDocumentUtils;

/**
 * This action calls the Agent with the specified request. It executes a Chat Completions (With History) operation based on the defined Agent. All agent configurations, such as the selected model, system prompt, tools, knowledge base or model parameter settings are used. 
 * If a request object is passed that already contains a system prompt, or a value for the parameters temperature, top P or max tokens, those values have priority and will not be overwritten by the agent configurations.
 * If a context object is passed, all variables are replaced in the system prompt. A response is returned that contains the final assistant's message.
 */
public class Agent_CallDocument_WithHistory extends UserAction<IMendixObject>
{
	private final java.lang.String Agent;
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	private final IMendixObject OptionalContextObject;

	public Agent_CallDocument_WithHistory(
		IContext context,
		java.lang.String _agent,
		IMendixObject _request,
		IMendixObject _optionalContextObject
	)
	{
		super(context);
		this.Agent = _agent;
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.OptionalContextObject = _optionalContextObject;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Request, "Request is required");			
			
			IMendixObject agentIMendixObject = AgentDocumentUtils.getAgentObjectFromDocument(Agent, getContext());
			
			return Core.userActionCall("AgentCommons." + Agent_Call_WithHistory.class.getSimpleName())
					.withParams(agentIMendixObject, Request.getMendixObject() , OptionalContextObject)
					.execute(getContext());
			
		} catch (Exception e) {
		    LOGGER.error(e);
		    return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Agent_CallDocument_WithHistory";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Agent_CallDocument_WithHistory.class);
	// END EXTRA CODE
}
