// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agenteditorcommons.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import agenteditorcommons.impl.MxLogger;

public class GetConstantValue extends UserAction<java.lang.String>
{
	private final java.lang.String QualifiedName;

	public GetConstantValue(
		IContext context,
		java.lang.String _qualifiedName
	)
	{
		super(context);
		this.QualifiedName = _qualifiedName;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			return Core.getConfiguration().getConstantValue(QualifiedName).toString();
		} catch (Exception e) {
		    LOGGER.error(e);
		    return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetConstantValue";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(GetConstantValue.class);
	// END EXTRA CODE
}
