// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxgenaiconnector.actions;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import mxgenaiconnector.impl.MxLogger;
import okhttp3.*;
import okhttp3.sse.*;
import static java.util.Objects.requireNonNull;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CountDownLatch;

public class Request_ChatCompletions_Stream extends UserAction<IMendixObject>
{
	private final java.lang.String RequestBodyJSON;
	/** @deprecated use MxCloudDeployedModel.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MxCloudDeployedModel;
	private final mxgenaiconnector.proxies.MxCloudDeployedModel MxCloudDeployedModel;
	private final java.lang.String StreamingResponseWriterId;

	public Request_ChatCompletions_Stream(
		IContext context,
		java.lang.String _requestBodyJSON,
		IMendixObject _mxCloudDeployedModel,
		java.lang.String _streamingResponseWriterId
	)
	{
		super(context);
		this.RequestBodyJSON = _requestBodyJSON;
		this.__MxCloudDeployedModel = _mxCloudDeployedModel;
		this.MxCloudDeployedModel = _mxCloudDeployedModel == null ? null : mxgenaiconnector.proxies.MxCloudDeployedModel.initialize(getContext(), _mxCloudDeployedModel);
		this.StreamingResponseWriterId = _streamingResponseWriterId;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		requireNonNull(this.RequestBodyJSON, "A Request object is required");
		requireNonNull(this.MxCloudDeployedModel, "A DeployedModel object is required");
		try {
			LOGGER.debug("Starting Request_ChatCompletions_Stream.");
			
			genaicommons.impl.StreamingImpl.createResponseMessage(getContext(),mxResponse);
			
			CountDownLatch latch = new CountDownLatch(1);
			
			OkHttpClient client = new OkHttpClient.Builder()
		            .readTimeout(0, java.util.concurrent.TimeUnit.MILLISECONDS)
		            .build();
	        
	        MediaType JSON = MediaType.get("application/json; charset=utf-8");
	        RequestBody requestBody = RequestBody.create(this.RequestBodyJSON, JSON);
	        String accessKey = encryption.proxies.microflows.Microflows.decrypt(getContext(),this.MxCloudDeployedModel.getMxCloudDeployedModel_Configuration().getAccessToken());
	        
	        Request mxCloudrequest = new Request.Builder()
	            .url(this.MxCloudDeployedModel.getMxCloudDeployedModel_Configuration().getResourceBaseUrl() + "/converse-stream")
	            .header("Accept", "text/event-stream")
	            .header("Content-Type", "application/json")
	            .header("x-api-key", accessKey)
	            .post(requestBody)
	            .build();
	        
	        EventSourceListener listener = new EventSourceListener() {
	            @Override
	            public void onOpen(EventSource eventSource, Response response) {
	            	
	            	LOGGER.debug("SSE Connection opened. HTTP " + response.code());
	       
	            }
	            
	            @Override
	            public void onEvent(EventSource eventSource, String id, String type, String data) {
	            	try {
		            	JsonNode rootNode = mapper.readTree(data);
		            	switch (type) {
		                case "MESSAGE_START":
		                    break;
		                    
		                case "CONTENT_BLOCK_START":
		                	createToolCall(rootNode);
		                    break;

		                case "CONTENT_BLOCK_DELTA":
		                	if (rootNode.path("contentBlockIndex").asInt() == toolContentBlockIndex) {
		                		updateToolCall(rootNode);
		                	} else {
			                    String chunkText = rootNode.path("delta").path("text").asText();
			                    genaicommons.impl.StreamingImpl.updateResponseText(mxResponse, chunkText);
			                    if (StreamingResponseWriterId != null) {
			                    	genaicommons.impl.StreamingImpl.pushChunkToUI(getContext(), StreamingResponseWriterId, chunkText);
			                    }
		                	}
		                    break;
		                case "CONTENT_BLOCK_STOP":
		                	if (rootNode.path("contentBlockIndex").asInt() == toolContentBlockIndex) {
		                		finishToolCall(rootNode);
		                	}
		                    break;

		                case "MESSAGE_STOP":
		                	String stopReason = rootNode.path("stopReason").asText();
		                	LOGGER.debug("Stop reason: " + stopReason);
		                    mxResponse.setStopReason(stopReason);
		                    break;

		                case "METADATA":
		                    setResponseMetadata(rootNode);
		                    break;

		                default:
		                    break;
		            }
	            	} catch (Exception e) {
        	            LOGGER.error("Error parsing JSON: " + e.getMessage());
        	        }
	                
	            }
	            
	            @Override
	            public void onClosed(EventSource eventSource) {
	            	LOGGER.debug("SSE Connection closed");
	            	latch.countDown(); // Signal completion
	            }
	            
	            @Override
	            public void onFailure(EventSource eventSource, Throwable t, Response response) {
            	    try {
		            	if (t != null) {
		            		if (t instanceof Exception) {
		            	        failureException = (Exception) t;
		            	    } else {
		            	        failureException = new Exception("Streaming failure", t);
		            	    }
		            	} else if (response != null) {
		            		String responseBody = null;
		                    if (response.body() != null) {
		                        responseBody = response.body().string();
		                    }
		            		//LOGGER.error("SSE HTTP failure: " + response.code() + " - " + response.message() + " - " + responseBody);
		            	    failureException = new IOException("HTTP " + response.code() + ": " + response.message() + " - " + responseBody);
		            	} else {
		            		//LOGGER.error("Unknown SSE failure");
		            	    failureException = new RuntimeException("Unknown SSE failure");
		            	}
            	    } catch (Exception e) {
            	        failureException = e;
            	    } finally {
            	        latch.countDown();
            	    }
	            }
	        };
	        
	        EventSource eventSource = EventSources.createFactory(client)
	            .newEventSource(mxCloudrequest, listener);
	        
	        try {
	        	latch.await(); // Wait indefinitely until stream completes
	        } catch (InterruptedException e) {
	            Thread.currentThread().interrupt();
	            eventSource.cancel();
	            throw e;
	        }
	        
	        eventSource.cancel();
	        
	        if (failureException !=  null) {
	        	throw failureException;
	        }
	        
	        mxResponse.getResponse_Message().setContent(mxResponse.getResponseText());
	        mxResponse.getResponse_Message().setMessage_ToolCall(mxToolCallList);
	        
	        return mxResponse.getMendixObject();
		        
		} catch (Exception e) {
			LOGGER.error("Something went wrong for model: " + this.MxCloudDeployedModel.getDisplayName() + "\n" + e);
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_ChatCompletions_Stream";
	}

	// BEGIN EXTRA CODE
	private static final mxgenaiconnector.impl.MxLogger LOGGER = new MxLogger(Request_ChatCompletions_Stream.class);
	
	private static final ObjectMapper mapper = new ObjectMapper();
	
	Exception failureException = null;
	
	genaicommons.proxies.Response mxResponse =  new genaicommons.proxies.Response(getContext());
	List<genaicommons.proxies.ToolCall> mxToolCallList = new ArrayList<genaicommons.proxies.ToolCall>();
	
	Integer toolContentBlockIndex = 10000;
	
	private void createToolCall(JsonNode rootNode) {
		
		genaicommons.proxies.ToolCall mxToolCall = new genaicommons.proxies.ToolCall(getContext());
		mxToolCall.setName(rootNode.path("start").path("toolUse").path("name").asText());
		mxToolCall.setToolCallId(rootNode.path("start").path("toolUse").path("toolUseId").asText());
		mxToolCallList.add(mxToolCall);
		
		toolContentBlockIndex = rootNode.path("contentBlockIndex").asInt();
	}
	
	private void updateToolCall(JsonNode rootNode) {
		
		genaicommons.proxies.ToolCall mxToolCall = mxToolCallList.get(mxToolCallList.size()-1);
		
		String currentText = mxToolCall.getInput();
		String chunkText = rootNode.path("delta").path("toolUse").path("input").asText();
		if (currentText == null) {
			mxToolCall.setInput(chunkText);
		}
		else {
			mxToolCall.setInput(currentText + chunkText);
		}
		
	}
	
	private void finishToolCall(JsonNode rootNode) {
		
		genaicommons.proxies.ToolCall mxToolCall = mxToolCallList.get(mxToolCallList.size()-1);
	
		if (mxToolCall.getInput() == null || mxToolCall.getInput().isBlank()) {
			mxToolCall.setInput("{}");
		}
		LOGGER.debug("Toolcall added to response.");
		
	}
	private void setResponseMetadata(JsonNode rootNode) {
		
		mxResponse.setRequestTokens(rootNode.path("usage").path("inputTokens").asInt());
		mxResponse.setResponseTokens(rootNode.path("usage").path("outputTokens").asInt());
		mxResponse.setTotalTokens(rootNode.path("usage").path("totalTokens").asInt());
		
	}
	// END EXTRA CODE
}
