// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pgvectorknowledgebase.actions;

import java.util.ArrayList;
import com.mendix.systemwideinterfaces.core.IContext;
import genaicommons.proxies.KnowledgeBaseChunk;
import pgvectorknowledgebase.impl.ChunkUtils;
import pgvectorknowledgebase.impl.MxLogger;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Use this operation to delete existing chunks and corresponding metadata in a knowledge base based on the MxObjectID. 
 * 
 * Input:
 * - MxObject: `This is the (original) Mendix object that the chunks in the knowledge base represent. Only chunks related to this Mendix object are to be deleted.
 * - DeployedKnowledgeBase: This is a knowledge base object that holds the knowledge base name and database connection details. This must be of type PgVectorKnowledgeBase.
 * 
 * Output:
 * - IsSuccess: This Boolean indicates if the deletion of data in the knowledge base was successful. This can be used for custom error-handling.
 * 
 * The DeployedKnowledgeBase entity passed must be of type PgVectorKnowledgeBase. It must contain the Name string attribute filled and a DatabaseConfiguration associated with the connection details to a PostgreSQL database server with the PgVector extension installed. This DatabaseConfiguration entity is typically configured at runtime or in after-startup logic. By providing the Name on the DeployedKnowledgeBase, you determine the knowledge base.
 */
public class KnowledgeBaseChunkList_Delete_ByMxObject extends UserAction<java.lang.Boolean>
{
	/** @deprecated use DeployedKnowledgeBase.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeployedKnowledgeBase;
	private final genaicommons.proxies.DeployedKnowledgeBase DeployedKnowledgeBase;
	private final IMendixObject MxObject;

	public KnowledgeBaseChunkList_Delete_ByMxObject(
		IContext context,
		IMendixObject _deployedKnowledgeBase,
		IMendixObject _mxObject
	)
	{
		super(context);
		this.__DeployedKnowledgeBase = _deployedKnowledgeBase;
		this.DeployedKnowledgeBase = _deployedKnowledgeBase == null ? null : genaicommons.proxies.DeployedKnowledgeBase.initialize(getContext(), _deployedKnowledgeBase);
		this.MxObject = _mxObject;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			java.util.List<KnowledgeBaseChunk> chunkList = new ArrayList<>();
			if (MxObject == null) {
				LOGGER.warn("No MxObject was passed, nothing was deleted.");
			}
			else {
				ChunkUtils.addChunkWithMxObjectID(getContext(), MxObject, chunkList);
			}
			return pgvectorknowledgebase.proxies.microflows.Microflows.knowledgeBaseChunkList_Delete_FromKnowledgeBase(getContext(), chunkList, DeployedKnowledgeBase);
		} catch (Error e) {
			LOGGER.error(e, "Something went wrong while deleting a chunk from the knowledge base.");
			return false;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "KnowledgeBaseChunkList_Delete_ByMxObject";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(KnowledgeBaseChunkList_Delete_ByMxObject.class);
	// END EXTRA CODE
}
