// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import genaicommons.impl.MxLogger;
import genaicommons.impl.ToolCollectionImpl;
import genaicommons.proxies.Tool;
import genaicommons.proxies.ToolCollection;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Adds a new Tool to a Request.
 * Parameters: 
 * - Request: The request to add the tool to.
 * - ArgumentInputLIst (optional): describe the input parameters of a tool.
 * - Name: The name of the tool to call.
 * - ToolOrchestrateMicroflow: The microflow that is called within this tool. Usually to pass the input to another serivce, but not to directly process the tool.
 * - Description (optional): A description of what the tool does, used by the model to choose when and how to call the tool.
 * 
 * The action returns empty if adding the tool was not successful (errors are logged).
 */
public class Request_AddTool extends UserAction<IMendixObject>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	/** @deprecated use com.mendix.utils.ListUtils.map(ArgumentInputList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __ArgumentInputList;
	private final java.util.List<genaicommons.proxies.ArgumentInput> ArgumentInputList;
	private final java.lang.String ToolOrchestrateMicroflow;
	private final java.lang.String Name;
	private final java.lang.String Description;

	public Request_AddTool(
		IContext context,
		IMendixObject _request,
		java.util.List<IMendixObject> _argumentInputList,
		java.lang.String _toolOrchestrateMicroflow,
		java.lang.String _name,
		java.lang.String _description
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.__ArgumentInputList = _argumentInputList;
		this.ArgumentInputList = java.util.Optional.ofNullable(_argumentInputList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(argumentInputListElement -> genaicommons.proxies.ArgumentInput.initialize(getContext(), argumentInputListElement))
			.collect(java.util.stream.Collectors.toList());
		this.ToolOrchestrateMicroflow = _toolOrchestrateMicroflow;
		this.Name = _name;
		this.Description = _description;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try{
			requireNonNull(Request, "Request is required.");
			//FunctionImpl.validateFunctionInput(FunctionMicroflow, ToolName);
			
			ToolCollection toolCollection = ToolCollectionImpl.getOrCreateToolCollection(getContext(), Request);
			
			return createTool(toolCollection).getMendixObject();

		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_AddTool";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new genaicommons.impl.MxLogger(Request_AddTool.class);
	
	public Tool createTool(ToolCollection toolCollection) throws CoreException {
		Tool tool = new Tool(getContext());
		
		tool.setMicroflow(ToolOrchestrateMicroflow);
		tool.setTool_ArgumentInput(ArgumentInputList);
		tool.setDescription(Description);
		tool.setName(Name);
		List<Tool> ToolList = toolCollection.getToolCollection_Tool();
		ToolList.add(tool);
		toolCollection.setToolCollection_Tool(ToolList); 
		return tool;
	}
	// END EXTRA CODE
}
